### ISSUE TITLE
★ character in tag breaks tag list

### ISSUE THREAD

**Issue by Darksonn** [rr-/szurubooru#121]
I created a tag with the ★ character in it. Most things still work, but the link on the taglist doesn't work, and shows the error:

    Tag ‘Mahou_Shoujo_Madokaâ\x98\x85Magica’ not found.

**Comment by rr-** [comment]
Someone (I'm not yet sure who) seems to screw things up when url-decoding the URL server-side; my initial bet would be on nginx cause it screwed `PATH_INFO` up before

**Comment by rr-** [comment]
Found the culprit here:

https://github.com/Pylons/waitress/blob/master/waitress/compat.py#L36

>```python
>from urllib.parse import unquote_to_bytes
>def unquote_bytes_to_wsgi(bytestring):
>   return unquote_to_bytes(bytestring).decode('latin-1')
>```

Before calling this function, the server sees `GET /tag/Madoka%E2%99%A5Magika HTTP/1.0` properly passed from nginx's `proxy_pass`. After calling this function, it becomes `/tag/Madokaâ¥Magika` rather than `/tag/Madoka♥Magika`.

Frankly the fact that it uses `latin-1` encoding rather than `UTF-8` sounds insane to me.

I'll investigate tomorrow if there's an RFC for this, cause gunicorn deserializes the URLs in pretty much the same way and that's too much of a coincidence.

**Comment by rr-** [comment]
There is and it advocates UTF-8.
https://tools.ietf.org/html/rfc3986
https://github.com/Pylons/waitress/issues/127

**Comment by rr-** [comment]
Looks like we have to do this after all, because that's what PEP 3333 WSGI ref seems to expect from the users, but I'll wait for the feedback in the linked issue

**Comment by rr-** [comment]
Fixed

**Comment by Darksonn** [comment]
This is not fixed. The tag の doesn't work.

**Comment by seanakabry** [comment]
Are there any other factors which might cause this?

I was experiencing this problem on two szurubooru installations on seemingly identical VPSs. Adding the UTF-8 charset to nginx's vhost config fixed this problem on one installation, but not the other. I can't think of any difference between the installations besides the content in their databases:

* Python 3.5.2
* gunicorn (version 19.7.0)
* nginx version: nginx/1.10.0 (Ubuntu)
* nodejs v7.7.4

Their config.yaml permissions are also identical.

I've tried restarting nginx and rebuilding the html after adding the charset,

**Comment by seanakabry** [comment]
There was a difference in the nginx vhost configs I didn't catch. For the VPS on which tags were breaking, I found:

```
location ~ ^/api/(.*)$ {
        proxy_pass http://127.0.0.1:6666/$1$is_args$args;
    }
```

and changed it to:

```
location ~ ^/api/(.*)$ {
        if ($request_uri ~* "/api/(.*)") {
            proxy_pass http://127.0.0.1:6666/$1;
        }
    }
```

which fixed it.
