### ISSUE TITLE
Feature request: mass change safety

### ISSUE THREAD

**Issue by Darksonn** [rr-/szurubooru#122]
We already have a mass-tagging feature, it would be natural to have a feature to change safety of lots of images at once, and it would be really useful to me.

I know there's a feature to do it on upload, which is good, but I currently have ~1300 images of varying safety all marked as safe.

**Comment by rr-** [comment]
I'd need some UI mocks, @tehoko do you feel up to this?

**Comment by tehoko** [comment]
It would have to be:
1. incorporated into mass tag, or
2. added next to mass tag button ("mass safety"?)

I'm leaning towards 2., because with 1. mass tag would be cluttered with buttons. Also, (currently) one cannot start mass tagging without entering a tag, so going with 1. kinda breaks UX in a few ways.

---

So, let's say we introduce a Mass safety button. (I don't like the name, but have no other idea.)

Right now, clicking on `Mass tag` hides this button and replaces it with mass tag-specific stuff. Similarly, `Mass safety` should also be hidden during mass tagging.

Entering mass safety editing should hide `Mass tag` and `Mass safety` buttons in a similar fashion, and only show `Stop editing safety` in their stead.

---

The mockup below uses 40 px squares with 4 px border. Inactive ones' background colors are at 50% opacity.

![image](https://cloud.githubusercontent.com/assets/2924029/22703559/dd5da576-ed64-11e6-817d-1c574b15901a.png)

I'm not sure if this is visible enough. Perhaps some ✓ mark should be added to selected safety?

**Comment by rr-** [comment]
Thanks, I'll come up with an example implementation somewhere this week (prolly near weekend)

**Comment by rr-** [comment]
Done:

- 0e4e9944319bb089c9d9ac67bfd8dd9f2c7c1986: client: rename 'mass tag' to 'bulk edit tags'
- 0dc7a4058e8e00b1dd878343f89b8c7a10cfcdaf: client/posts: refactor bulk tag editor
- 1caf76b1b2e2aaef507b1936a2c5a66c2df140f5: client/posts: add bulk safety editing (#122)
