### ISSUE TITLE
Feature request: permission setting for featured posts viewing and data obfuscation

### ISSUE THREAD

**Issue by mserajnik** [rr-/szurubooru#135]
We currently already have the option to prevent users from seeing any posts by setting `posts:list` and `posts:view` (and possibly some other settings as well – these two are the only ones set to `anonymous` by default though) to a higher permission level than the users's.

It would be nice if this would also be possible for the featured posts so we can completely block out users from seeing any posts (those without technical knowledge to fish for IDs in `/data/posts/` at least). The setting could be called `posts:view_featured`.

**EDIT:** Additional question, didn't want to open a new issue for this. Regarding ID "fishing": I was a little bit worried at first because all the post media are just saved in the format `post_id.ext` in `/data/posts/`. I'd have preferred saving them with a unique ID so fishing wouldn't be that easy. But I guess I can instead just change the path in `data_dir` to something ludicrous like `/srv/www/booru/client/public/data23b77938939623ed5426c419a6f9963cfe27a664751613dff6b892ac5aa7edcb/`, so if I remove all the privileges from `anonymous` users they would need to be able to guess the hash, right? This will still work, the final directory doesn't have to be called `data`?

**EDIT 2:** After some further digging I realized that `tags.json` will always be loaded when not logged in, even when `tags:list` and `tag_categories:list` are set to `regular` or higher. Yes, it even says so in `config.yaml.dist`, but I didn't think it would actually load the file by itself just by visiting the app (I thought an `anonymous` user would still need to manually fish for the file if the permissions are set accordingly, just like with posts itself).

This actually has two implications: first, every visitor can just read all the tags, as long as he knows how to operate the Network tab in the dev tools. Might or might not be a big deal depending on the content. In my case, a friend of mine stumbled upon this on my test installation where I imported some random (unsafe) images including tags from Gelbooru to test the tagging features. It was fun for him but less fun for me. :D But that makes it pretty bad if I were to use szurubooru in private where I don't want other people to know what kind of porn I prefer.

Second: `app.min.js` actually has the full path to the `data` directory because that's where `tags.json` is stored. This makes the idea from my first edit unusable since any visitor can just get the URL from `app.min.js` and the proceed fishing for actual files. This is actually pretty bad for private usage, even when I just, e.g., want to have a place to share photos with my family.

I realize that a booru is mainly used collaboratively but the feature set of szurubooru also makes it a great choice for people wanting to self-host an application for their images instead of uploading everything to Google's or Apple's servers. So I think it would be nice if we could tackle those issues to make it better to use for private purposes.

Of course, one could always just set up basic auth in addition, but that makes it harder to remove users since you'd not only need to delete the account but also change the basic auth credentials (and tell everyone else who should still be able to use szurubooru the updated credentials) or set up multiple credentials (or do it via groups). No matter how you do that, it'll always be a hassle.

What do you think?

**EDIT 3:** I've started working on obfuscating `tags.json` myself, doesn't work yet (I also have no experience with Python), but I'll report back so you can see if this is something you'd like to have in the main repository as well.

**Comment by rr-** [comment]
I've considered having the file names consist of unique non-discoverable numbers earlier, but eventually I dropped that idea, although I don't remember the reason why. I might revisit that idea but this time I'd keep the post IDs like this: `2151_f8f19a09.jpg`, so that users can still get to the post page when given its permalink by someone "inside".

Regarding `tags.json` and `tag-categories.json`: this is to avoid querying the database when fetching lots of posts, each of which needs to hold an array of tags (and the client needs to know categories of these tags so it can colorize them in the sidebar).
It might be a good idea to add server-side caching and serving everything with each request, rather than relying on hacks like that and having the client download 1MB worth of information about tags and their categories - especially considering how this approach generates some race conditions when the user loads the page for the first time.

If I were to implement any of these, it'd need backwards incompatibility though. This is something szurubooru didn't need to care about before, but I think bumping the major version should be enough.

Let me know what you think of these ideas...

**Comment by mserajnik** [comment]
Thank you for your input, I've tried coming up with something myself: https://github.com/mserajnik/szurubooru/commit/236818f2aa2d8cc39e4a690a4b84bdbdbdca37a8

I didn't know about `tag-categories.json` until now, so this would just work for `tags.json` (and it checks all the `tag_categories` permissions too since I wrongly assumed these are served via `tags.json` as well).

It seems to work, e.g., if I set all the `tag` and `tag_categories` permissions to `regular` or higher and am logged out, it doesn't fetch `tags.json` (and the user doesn't know what the path to the `data` directory is nor the real filename of `tags.json`). Now when I log in, it does (but I need to manually refresh after login, so not ideal).

Just a quick idea how it could be done with obfuscation alone. The code is not elegant at all and not something I'd like to see in the main repo. I've basically just duplicated some of your code and adapted it until it kinda worked. :P

But I like your idea about serving everything with each request better anyway.

Regarding post IDs: again, this wouldn't be an issue if `data` could have a custom name (which it can as long as the `data` path for fetching `tags.json` and `tag_categories.json` isn't hardcoded and instead fetched from the server like in my poor example code), but having each file named `2151_f8f19a09.jpg` instead of `1.jpg` would of course be even better than that.

How about separating the post ID and the filename altogether? So you could keep the current ID and just add another database field for the filename. I'm not sure of how much of an performance impact it would have on the database if it were to compare to `2151_f8f19a09` instead of `1` when looking for a post – probably negligible. But afaik you are also using the IDs for sorting, right?

Having ID and filename separated would also mean that the filename could be anything – like a `SHA1` hash + timestamp to rule out any (unlikely) collisions.

**Comment by rr-** [comment]
(I'm not sure if there's even such a thing like `tag-categories.json` - I was only speaking from my memory, maybe they're stored in `tags.json`)

>But afaik you are also using the IDs for sorting, right?

Yep, IIRC that's the case.
I think the reason I wanted to avoid having custom filenames was to avoid querying the DB to get the thumbnail URLs... or something like that... but I can't think of any place where it actually could save anything.

>So you could keep the current ID and just add another database field for the filename

This is what I had in mind and wanted to keep the post ID in its filename only so that the user could go from `/data/posts/123_1234abcd.jpg` to `/posts/123` (for example to fav the post).

I think I will implement custom post and thumbnail file names some time next week.
I'll have to think how to efficiently implement `tags.json` replacement and this will come second.

I also think I will spread out the file names across multiple directories (like git does) to avoid querying the file system to locate a file within a single directory containing 10s of thousands of files.

**Comment by rr-** [comment]
Aha, `tags.json` is also used by the client to make in-memory auto completion rather than querying the server after each key press, so whatever replacement I come up with, it would be preferable if it stayed within the same order of magnitude in terms of performance :)

**Comment by mserajnik** [comment]
> I think I will implement custom post and thumbnail file names some time next week.
I'll have to think how to efficiently implement tags.json replacement and this will come second.

Cool, looking forward to it. I will be on vacation starting this Saturday so I won't be able to provide any feedback until I get back (around September 10).

> Aha, tags.json is also used by the client to make in-memory auto completion rather than querying the server after each key press, so whatever replacement I come up with, it would be preferable if it stayed within the same order of magnitude in terms of performance :)

How about using [IndexedDB](https://developer.mozilla.org/de/docs/IndexedDB) instead of a file? I don't think there would be any perceivable difference in speed compared to the current solution. Browser support seems pretty good too: http://caniuse.com/#search=indexeddb

**Comment by rr-** [comment]
Let's split this into multiple issues so I can track the work easier.

**Comment by rr-** [comment]
gt
