### ISSUE TITLE
Feature request: Album like grouping

### ISSUE THREAD

**Issue by joshuaavalon** [rr-/szurubooru#162]
A feature that allows grouping a set of images would be nice. A set of images that have order to view. It would be nice. You can use tag to this. But you not order the images or give it a title.

**Comment by rr-** [comment]
Post relationships achieve that goal to a certain degree.

**Comment by joshuaavalon** [comment]
@rr- Post relationships is current state is a bit useless in my opinion. If you want to make a 50 post album, you need to add the relationships individually (49 times). It would be easier if I create dedicated tag instead.

Using dedicated tag is a work around but you cannot maintain the order or give it a title.

**Comment by rr-** [comment]
Yeah, that's why I added "to a certain degree" :)

**Comment by rr-** [comment]
(technical discussion follows)

@ReAnzu  maybe your idea of associating multiple files with a single post would work here?
I'd rather avoid creating a new DB table `post_groups` since that would greatly complicate post listing.

**Comment by joshuaavalon** [comment]
I don't think you should treat post in a album different from normal post. Let the album to have all the tags will be a mess. The user can find the post by tag and discover to the album anyway. 

I think a album should only contain title, description and post with order. Searching album for title only should be enough. While integrating all into one search will be great, I think it should be on a separate page for browsing and album.

**Comment by mserajnik** [comment]
Just a quick idea from my side since this is also something I‘d like to see:

The way hydrus does it is it allows you to sort by namespace (= tag categories). You could for example sort by creator-series-title-page (in that order). Depending on the DB structure, this could be a very heavy query though, so maybe just sorting by a single tag category would suffice (because you coul still add a tag like sort:creator-series-title-page manually and sort by that – requires work on the user side as well, but I‘m currently writing a server that uses the hydrus server DB and does it this way and it works quite well as a workaround).

Just throwing this out in case this might be easier to implement.

**Comment by ReAnzu** [comment]
I think this sounds a lot like the Danbooru concept of pools (http://testbooru.donmai.us/pools, http://testbooru.donmai.us/pools/5). Which, in the most basic implementation would involve atleast two more tables separate from the post tables, along with a new view, a new api endpoint, and some modifications to existing views/controls.

```
pool:
    title
    description
    owner

pool_post:
    post
    order
```

- I imagine an additional desired feature would be a mass add post to pool from the post search page. I think this would probably function similarly to the mass tag feature.
- The post edit view would need an input field to add a post to one or more pools. (Similar to how the tag field works now, along with auto suggestions of pools to add it to)
- It might be nice to have a message on the post page that a post belongs to one or more pools, with a link to the search for pools with this post in them.

This is something I've considered adding, and is on my list of someday ideas. however it wasn't near the top because I'm not particularly familiar with the codebase and this involves a decent amount of UI changes. Not that I'm opposed to working on this sooner than later as I've been picking up the codebase quickly thanks @rr-. 

I'm not sure associating different images with a post is ideal in this case. That suggestion was more around allowing multiple formats for the same post, and then the administrator could define default mime types to display. I think in particular the view post UI wouldn't be an ideal place to show a bunch of thumbnails representing a user defined collection of ordered images.

I like the idea of being able to define an order to sorting via tags, but it raises a few questions. 
- Does a sort involving a tag imply that the tag has to be part of all the posts searched?
- Would we need some way to save queries and serve them up as suggestions, or provide them on a separate page? It seems like having to enter the same, long, query on each visit might kill the feature by way of making it inconvenient to use. 

I think the advanced sorting would be missing at least two of the mentioned desired features however.
- A title/description for the collection of posts.
- User defined,

**Comment by mserajnik** [comment]
@ReAnzu:

In regards to your questions sorting via tag categories:

- No, the post doesn't need to have a tag with the category that is used for sorting. If it doesn't it just gets moved to the end of the result (you could just sort such posts by their ID or something).
- If it was strictly sorting by tag categories, I'd maybe do it via a separate select box in the style of [chosen](https://harvesthq.github.io/chosen/). Because having to write something like `sort:category:creator` would of course be tedious.

In regards to missing features:

- Title/description: agreed, that would of course be missing and could only be worked around by tags
- Used defined post order: as I've mentioned, hydrus allows for sorting by several namespaces (categories) at once, e.g. `creator-series-title-page`. All your posts you want to group up would have the same `creator`, `series` and `title`, but a different `page` each time. If you're limited to sorting by a single category (which would be a way lighter query), you'd need tags like `creator-series-title-1`, `creator-series-title-2` on each post, which is not ideal (I don't personally mind it though because I just automate the creation of such a tag with a small script based on other tags the post has, but it's not user friendly).

But I think I'd lean towards your pools suggestion as well. After reading through OPs request again I think that I'm shooting off target a bit with my suggestion. I still think sorting by category would be cool to have, but it doesn't really solve everything OP would like to see.

**Comment by rr-** [comment]
I like @ReAnzu 's ideas save for pool auto suggestions. I think the UI for tag suggestions is a failure, so I'd avoid copying it in another part of the application.

Getting navigation within an album right would be tricky since there's already ❬ and ❭ used for navigation between posts.

**Comment by mserajnik** [comment]
On the topic of auto suggestions:

I think auto suggestions are not necessary for the intended use cases. If I understand the proposal correctly, the main benefit of having albums is being to able to group together posts while also arranging these in a specific order inside the album.

To me, that sounds like a nice way to group pages (= posts) of a manga (or any other series of images that belong to a bigger set) together. Those can (and often will) have very different tags depending on the content, e.g. one image could show two characters speaking and another one could show a landscape. So auto suggesting an album based on tags would probably fail in these cases.

Another good use case (imho) might be to group together posts based on „moods“ (I‘m sure there is a better word), e.g., _nice landscapes_. Tags might no be sufficient here because one would probably tag an image of a beach and a mountain range very differently (so auto suggestion would fail here as well), while they both fit the description of _nice landscapes_. The definition of _nice landscapes_ is also something that‘s up to the individual user so adding that as a tag to group together such posts in that way (instead of using an album) is not a good idea (because on a installation with multiple users you probably don‘t want any tags stating personal opinions, only facts).

I can‘t think of any good use case for albums that would require auto suggestions where just addings tags to group such posts together would not be the more logical thing to do.

**Comment by ReAnzu** [comment]
I see the point about auto suggesting. Pools/Albums really are more of a personal user thing so it doesn't make sense to suggest adding an image to a pool. I think when I wrote about auto suggesting albums I wasn't particularly clear, looking back at the comment I think it was the idea that just like when you start typing tags, an ajax call will suggest tags matching a like query of what you've typed, sorted by usage.

And in thinking about functionality there are perhaps a few more considerations.
- Should albums have a privacy feature where only the owner can view it? -- I'm leaning against this, it seems like an anti-feature.
- Should albums only be editable by the owner, or should albums be able to have 'moderators'? -- Maybe this is something that could come later after a groups functionality? Though I'm still brainstorming around whether such functionality would be useful. ~
- Should albums be able to be featured? If featured should they act like a slideshow, choosing a random image from the album? Or should a collage of sorts be generated when featured and displayed? ~+
- Should there be limits to how many albums a user can own/manage? ~
- Should albums be able to have their own tags that can be searched? +
- Should albums be able to have score like posts? +
- Should albums be able to have comments? -

It sounds like album would be a fitting name for this feature, does anyone know/have ideas why other board software chose to label them as pools? Perhaps album is a name that is overly focused on pictures, where a pool could have pages in a web comic in order, or pages of a manga. Though, I'm not really sure a pool is a great way to display such media, and a dedicated feature might make more sense for that. Especially since for collected works like that there facts that make sense to tag on a collection, that a post might not have.

**Comment by rr-** [comment]
>Should albums have a privacy feature where only the owner can view it?

No, users have their HDDs for just that.

>Should albums only be editable by the owner, or should albums be able to have 'moderators'?

Everyone should have permission to every album. If someone can't play nice they deserve to get banned anyway.

`szurubooru` used to have much more complex permission system where one could edit only their own posts, and site administrators could pretend there is no NSFW content on the site through specifying who gets to see NSFW posts. It was bloatware: it complicated the code for no real gain as nobody really used this feature.

>Should albums be able to be featured?

Nah, I'd feature only regular posts (= also posts that happen to belong to some album).

>Should there be limits to how many albums a user can own/manage?

No, just like there is no limit how many posts a user can upload.

>Should albums be able to have their own tags that can be searched?

Yes*.

>Should albums be able to have score like posts?

IDK. I'd say yes*.

>Should albums be able to have comments?

If one can rate an album, one should also have the ability to comment on it, IMO*.

---

\* Generally I'd rather keep albums as lightweight as possible. IMHO they should be more of a "multi posts" like on pixiv (= each post in the album shares its artifacts such as comments, score, tags, relations, whatever) rather than gelbooru's pools "pictures I think look nice". We have tags for the latter.

**Comment by ReAnzu** [comment]
Ok, so thinking of this as a structure, and keeping it basic. 

- Albums consist of posts, and post entries in an album have a defined order, stored on the linking.
- Albums do not have their own comments, tags or relations. However they inherit all the tags, comments and relations from their members.
- Album Score is a sum of the scores of it's posts.

So, this way albums are really just custom orderable collections of images without a lot of functionality of their own. The beauty of which is they simply serve as a way to group id's when searching. 
- Want to find all comments for an album? Get the album ID, grab all the posts in it and do an time ordered search of all comments on those posts. 
- Want to sort albums by score, group by and sum with a database call.

Hearing where szurubooru came from in regards to permissions, I think I now understand the permission system better. it is slightly tedious to add permissions and preventing custom groups definitely keeps things simple.

**Comment by ReAnzu** [comment]
In regards to the multiple images per post, I'm really starting to lean away from that. It does seem like the scope of the changes required would outweigh the usefulness of the feature.

I think my biggest pain point is I have some large files that I load and I'd prefer to have a resized default smaller, resized image, with the option to load the large image if I need to. But that is a different feature request when I figure out if that really solves my issue.

**Comment by Hunternif** [comment]
Is anyone working on this?

**Comment by rr-** [comment]
I'm not.

**Comment by GlassedSilver** [comment]
Adding my vote for this feature.

**Comment by MaxValue** [comment]
Mine too.

**Comment by catchra** [comment]
Mine too. will be great for CG galleries
