### ISSUE TITLE
Docker deployment

### ISSUE THREAD

**Issue by joshuaavalon** [rr-/szurubooru#169]
I am experimenting on docker deployment. Will you accept pull request on that?

**Comment by joshuaavalon** [comment]
I want to confirm is the version compatibility for postgres and elasticsearch. I am trying postgres 10.4 and elasticsearch 6.3.0. It does not seem to have problems.

**Comment by rr-** [comment]
There shouldn't be any problems; I'm running an instance with elasticsearch 6.2.3-1 and postgresql 10.3-1.

**Comment by joshuaavalon** [comment]
@rr- Would you mind to help test it out? https://github.com/joshuaavalon/szurubooru/tree/docker

You need a `config.yaml` at the project folder with  `data_dir: '/data'` and `database: 'postgres://szurubooru:szurubooru@postgres:5432/szurubooru'`.

Then, `docker-compose up -d` will works. Currently there are two Dockerfile for the server. `Dockerfile.server` is based on Debian while `Dockerfile.server.alpine` is based on Alpine.

The Debian version should run fine and fast to build but the image is huge (~1.1GB).
The Alpine version is what worries me. I afraid I may miss some dependency.  The Alpine version is much smaller (~660MB) but it takes a long time to build (about 45 mins on my Digital Ocean VM) because there are no compiled library for Alpine and it needs to compile every libraries in the ``requirements.txt`.

I want you to help testing on the Alpine version.

Also, you can either let the user build the image (docker-compose) or provide a image on DockerHub. What is your opinion on this?

**Comment by sgsunder** [comment]
@joshuaavalon you can look at [my docker deployment](https://github.com/sgsunder/szurubooru/tree/docker), it works similar to yours but incorporates the latest commit. I use `python:3.6-slim` which is much smaller than `python:3.6-jessie`, but doesn't need to build python packages like alpine does because of musl. I also custom build ffmpeg with only the needed features to shrink the image even more. The backend image is about 500MB and the frontend is about 20MB.

Now that the PR I've submitted has been merged, I can probably make another PR for my docker deployment soon, but the smart thing would be to work together with Josh first. I need to add a readme file, too.
The smarter

**Comment by joshuaavalon** [comment]
@sgsunder `python:3.6-slim` is a much better solution. I remove Alpine and Jessie. I skimmed through your docker deployment. I see you extract many configurations to `docker-compose.yml` with extract script but I prefer a simpler approach with at little change to original deployment at possible.

**Comment by rr-** [comment]
Thanks to recent changes from @sgsunder, the dockerization process should be much simpler now.
