### ISSUE TITLE
Feature request: Extra metadata

### ISSUE THREAD

**Issue by joshuaavalon** [rr-/szurubooru#190]
When we upload the images, the source images always come with some metadata. It would be nice if we can include some of them.

For example:

* Title
* Description
* Source URL

**Comment by mserajnik** [comment]
Imho, that's what tags are for. You can easily just have namespaced tags like `title:lorem` and `description:lorem ipsum dolor sit amet`. Plus, there's notes (where you could put the source).

What would be the benefit of having these as separate fields?

**Comment by joshuaavalon** [comment]
@mserajnik Title, description, source URL does not like tags because they are most likely be unique. Also, this will make the tag very long for not reason.

> What would be the benefit of having these as separate fields

You can have them show properly instead of showing all of them on side. And you don't want to search them when you are search for tags. Also, if we have search on Google,  why do we just include the link to original source?

From what you are saying, you may misunderstand what I mean for those fields. 
Let use a  random art on [deviantart](https://www.deviantart.com/panjoool/art/Breath-of-fear-759523884) as an example.

Title: Breath of fear
Description: Fear gives strength, Fear of death gives me the strength to fight for life, without fear there will be no courage. I will not die today, I will fight for my life and defeat my fears
Source URL: https://www.deviantart.com/panjoool/art/Breath-of-fear-759523884

Imagine you have a tag `description:Fear gives strength, Fear of death gives me the strength to fight for life, without fear there will be no courage. I will not die today, I will fight for my life and defeat my fears` on the side. How would be this be suitable as a tag?

**Comment by mserajnik** [comment]
Thanks for expanding your explanation.

> Imagine you have a tag `description:Fear gives strength, Fear of death gives me the strength to fight for life, without fear there will be no courage. I will not die today, I will fight for my life and defeat my fears` on the side. How would be this be suitable as a tag?

I agree, that would be pretty dumb, but that's also why I wrote

> Plus, there's notes

This is already a "catch all" field for everything else that doesn't really fit into tags. Seeing as other major booru softwares (Danbooru/Gelbooru) don't have title or description fields, this sounds like a pretty niche use case to me (because I would expect those large boards to already have it if it's a functionality a majority of users would like see).

Speaking only for myself, I usually tag with `title:xyz` to group together images in a series, manga pages etc. To describe images, I solely use tags. If I had a description like yours that doesn't state facts about the image, I would put that into notes. Because that's basically just like flavour text on Magic: The Gathering cards.

Having a field for the source is something I could see being useful, if only just to make it easier to find more creations from the same artist or to attribute works. We already do have Google image search and IQDB to help out with that. Then again, I stand by my initial statement that that's also something that could just go into the notes.

Just to clarify: I'm not really against those ideas, but implementing something only a small percentage of users will use is not always the best thing, even if it is just pretty small change like this. Because if we did this with every small change, we would bloat up szurubooru pretty fast. That's why I'm trying to see if those additions are something that would benefit "everyone" using the software (which the source field might potentially be).

But let's hear what @rr- thinks about it.

**Comment by rr-** [comment]
`szurubooru` used to have a source field but nobody used it, and thus I removed it (IIRC it's still accessible through the API if you want).

I think fields such as `title` and `description` belong to sites such as DeviantArt, FlickR or Pixiv where authors upload their own content. I certainly wouldn't want to occupy any vertical space for this feature.

**Comment by noirscape** [comment]
For what it's worth, e621 does support this feature in the form of a text box in which anything can be put (typically any comments the artist added to it). That said, I think that the same could be acomplished with a top comment.

**Comment by joshuaavalon** [comment]
@noirscape That's my current solution. I guess I will close this request.

**Comment by gnarpaws** [comment]
A description field, which could contain for example a manual "transcription" or OCR from the posted image would be useful for handling memes. (Fulltext search)
