### ISSUE TITLE
Hydrus Integration for Szurubooru

### ISSUE THREAD

**Issue by antonizoon** [rr-/szurubooru#201]
Another option for p2p file syncing or sharing of booru files is to use the Hydrus Network, which syncs images and tags of large image collections. Although there are attempts at [creating a webUI for hydrus](https://github.com/mserajnik/hydrusrvue), they have not yet reached full maturity as a booru since they don't offer public upload. Hydrus is also written in python which can help.

https://hydrusnetwork.github.io/hydrus/

Now, there exists the following third-party integrations with Szurubooru that can be used right now to mass import media from the Hydrus Network, though it is a one way sync.

https://github.com/mserajnik/szuruporter

https://github.com/mserajnik/quicktagr

[Szurubooru does have an API](https://github.com/rr-/szurubooru/blob/master/API.md) for a Hydrus client to at least pull from as stated in the prior issue here: https://github.com/rr-/szurubooru/issues/131

I may update this issue with our possible implementation setup of utilizing szuruporter with an unmodified szurubooru instance, which will guide us to better ways of integrating the two great systems together.

**Comment by mserajnik** [comment]
Thanks for checking out my projects. Although I‘m not sure if this was coincidence? :D

First, let‘s start off by clarifying that the hydrus network _does not_ by default sync files/tags with anything. To achieve this, one has to either run their own hydrus network server instance (and share the access to it with other users) or connect to an existing server, mainly the one run by the hydrus network developer himself.

Even when it‘s set up like that, it doesn‘t really _sync_ data. The client downloads the latest data from the server in 24h intervals and the user can decide to keep the data or discard it. The other direction (uploading the the client to the server) is only ever done on demand and can‘t be automatized.

That said, hydrus network can certainly be used to exchange data with other people by making the server act as a „central hub“ where data from various sources is gathered.

As for the tools you‘ve mentioned, since the are all written by me, I‘m going to outline some things.

> […] webUI for hydrus

This is actually a combination of a server anf client application, with the server only copying data from a hydrus server instance (temporarily), and serving it to the client.

It‘s only intended as a viewer by design, because actually writing to the same database hydrus server uses isn‘t really feasible without a lot of scaffolding around it that ensures data integrity.

Even then, it‘s imho too likely to corrupt something in the process, the nature of SQLite not really benefitting the idea of multiple concurrent accesses to the database. Plus, hydrus server certainly isn‘t written in a way it expects another application to write to the same data source, complicating things further.

To sum up, I think it‘s doable to create a read/write wev frontend for hydrus server, but I don‘t think it‘s worth the trouble right now. Probably better to wait for the public API the hydrus server developer has already teased in a recent release post.

> quicktagr

This one is actually completely unrelated to hydrus or any other way to move data.

It’s just a little tool intended to make it easier/faster to tag files from a fixed set of tags, although you could argue that it only works for a very limited set. It gets increasingly slower the more files and tags you have, up to the point where it doesn‘t really provide much use anymore at all.

> szuruporter

While it can currently only ever add and modify data in szurubooru, adding the ability to delete would make it possible to set up a shared directory that it would sync with szurubooru via cron job and where hydrus would import/export from/to automatically (hydrus already offers that feature).

This would still require quite a complicated setup and the hydrus client would need to be connected to a hydrus server instance as mentioned before.

Looking at your other (IPFS) proposal, I‘m not sure what you‘re trying to achieve. Do you just want a way to „back up“ data decentralized or is it also about accessing that data in different ways, other than by using the szurubooru frontend or API directly?

**Comment by DonaldTsang** [comment]
Hydrus is a very powerful scraper and DB, but only Szuru has a WebUI to handle multiple clients (Hydrus uses SQLite, a unique DB structure and can only handle a small amount of concurrent clients)

**Comment by rr-** [comment]
This requires either

1. third party application such as the mentioned szuruporter that already exists
2. rewriting szurubooru so that it uses hydrus
3. rewriting hydrus ui so that it accepts multiple clients

The projects are not compatible with each other.

**Comment by DonaldTsang** [comment]
@rr- I would like to make a formal report that the Hydrus API is in the works.
