### ISSUE TITLE
Feature request: Changing tag category order

### ISSUE THREAD

**Issue by noirscape** [rr-/szurubooru#209]
At the moment, tags are sorted on post pages in the category order in which the category is made.

It would be handy to be able to change this order, since as it currently stands, if a category is added later on, the tags for it will always be at the top, which might not always be desirable.

For an example use case:

- Assume I have the categories `artist` and `character`.
- I decide to add a new category called `copyright`.
- `copyright` is now placed below `artist` and `character`, while I'd like to prefer it to be above these categories.

**Comment by GlassedSilver** [comment]
Seems to be alphabetical for me? I tried recreating tag categories (with a fairly fresh install, mind you) and no luck... Order of creation didn't change a thing.

**Comment by sgsunder** [comment]
Yes, it's supposed to be alphabetical. An inelegant workaround would be to use `01_copyright`, `02_artist`, `03_character`, which is what I do.

However, I do this to be a properly implemented feature sometime in the future.

**Comment by neobooru** [comment]
The most obvious solution here would be to add an `order`, `index` or `position` column and use that to order the categories. The easiest thing would be to just use the orders 1, 2, 3, 4, 5 etc.

| category  | order |
|-----------|-------|
| copyright | 1     |
| character | 2     |
| artist    | 3     |
| default   | 4     |
| meta      | 5     |

The downside with this approach is that you need to update (worst case scenario) all entries when you change the order for one item.

An alternative approach would be to use 100, 200, 300, etc. In this case you can insert a new entry without updating the others.

| category  | order |
|-----------|-------|
| copyright | 100     |
| character | 200    |
| artist    | 250     |
| default   | 275     |
| meta      | 300     |

The downside with this approach is that you make insertion more difficult (you need to calculate what number to use) and at a certain point you still need to update other entries (thought by using larger numbers like 1'000'000 and 2'000'000 you realistically would never need to).

There are also more advanced techniques [demonstrated here](https://begriffs.com/posts/2018-03-20-user-defined-order.html) but those are overkill in my opinion. I kinda like the idea of ordering by a string [as seen here](https://stackoverflow.com/a/49956113/2125072) but that also makes stuff more complicated.

I personally like the first approach the most, and because you usually don't have more than 10 categories it really wouldn't slow the database down in any noticeable manner.

Thoughts?

**Comment by sgsunder** [comment]
I think it depends on how we want users to implement this in UI. If we're going to implement a nice, fancy, drag-n-drop UI to set the category order, I would agree that the first one is best, but if we're going to have users manually enter the "order" number, then I would say the second is best.

Agreed on avoiding the more advanced stuff, too. Users would be unlikely to have more than a few dozen categories, and would be changing them rarely anyway, so no need to look for crazy performance-optimized solutions.
