### ISSUE TITLE
Add instructions to upgrade postgresql to install.md

### ISSUE THREAD

**Issue by noirscape** [rr-/szurubooru#213]
At the moment, the deployment setup makes use of docker and uses `.env` files to prevent users from having to manually modify `docker-compose.yml`. Unfortunately, as a side effect of this, this means that users that install szurubooru will eventually run into an issue when postgres gets a major release.

As postgres is maintained through docker and postgres's update_db doesn't work when ran like this: `docker-compose run sql pg_upgrade`, this means I have to manually modify the `docker-compose.yml` to pin the major release that I installed szurubooru on.

**Comment by joshuaavalon** [comment]
@rr-  How about pining the major version of postgres?

docker-library/postgres#37 suggests that using `pg_dumpall` to backup and restore to a new version.

**Comment by rr-** [comment]
>docker-library/postgres#37 suggests that using pg_dumpall to backup and restore to a new version.

That's pretty much how it works: you export the whole database with the old Postgres version, then upgrade Postgres, then you import the data with the new version. Of course this means significant service downtime.

>@rr- How about pining the major version of postgres?

I'm not sure how other people feel about this, but I like it since I have had bad experiences with Postgres updates – basically every half a year, a full system upgrade that happened to update Postgres, broke our website and I always noticed it pretty late and had to do emergency db migrations. Of course this can be prevented with some monitoring scripts or by using a saner distribution than Arch Linux, but that is beside the point.

**Comment by sgsunder** [comment]
We can switch `image: postgres:alpine` to `image: postgres:11-alpine` or even an earlier version in the docker compose file. Would this be acceptable?

**Comment by GlassedSilver** [comment]
> We can switch `image: postgres:alpine` to `image: postgres:11-alpine` or even an earlier version in the docker compose file. Would this be acceptable?

At some point we might run into a situation where we might want to use a newer version for feature or stability improvements (or speed) and if that happens a little later we might be looking at an unsupported  upgrade path.

Oh and let's not forget old versions are fine for things like you running your own little booru for private needs in your own LAN like I do, but someone who runs an actual public site would probably prefer staying up to date at least with some delay.

**Comment by sgsunder** [comment]
Switching to `postgres:11-alpine` will still give you patches and minor version number upgrades, it would just keep you from upgrading the major version number to 12 or later. And Postgres 11's end of life is scheduled for November 9th, 2023 according to the Postgres website, so I don't think that would be an issue anytime soon.

November 9, 2023
--




November 9, 2023
--

**Comment by GlassedSilver** [comment]
Fair enough... Still worth keeping in mind what OP said.

**Comment by noirscape** [comment]
Dunno if my input was asked for, but I'm personally fine with version pinning `postgres`.
