### ISSUE TITLE
Bug: Automatic password recovery emails are missing the base URI

### ISSUE THREAD

**Issue by TiredSysOp** [rr-/szurubooru#256]
Will also bring up #193 as well, having a option to enter a domain or subdomain in the config is a nice workaround.

![bug](https://user-images.githubusercontent.com/31832099/56880020-0463f400-6a53-11e9-96a2-d2e379ed9e43.png)

The booru has it's name set to a name that will resolve to itself if entered in an address bar, for the life of me I can't get the base uri to show in the link in the password recovery emails

Currenly using latest docker version and it sits behind nginx, using remote smtp server

Cheers

**Comment by neobooru** [comment]
I solved this issue for me as seen in the commit linked above (https://github.com/neobooru/szurubooru/commit/47760de37c5a57ed4214bf22fe88a5039df8f746), however this solution changes the config.yml in some 'breaking' ways, which is why I haven't opened a pull request yet. Any thoughts about this solution, or possible alternatives?

This would also solve #193

**Comment by sgsunder** [comment]
@neobooru I think that your solution is a good idea, I would open up a PR!

**Comment by sgsunder** [comment]
Resolved in #265 and 80d272d
