### ISSUE TITLE
[Suggestion] Allow spaces in tags

### ISSUE THREAD

**Issue by GlassedSilver** [rr-/szurubooru#258]
I think the title is pretty self-explanatory. It'd be very welcome to be able to use spaces in tags.

Underscores are the work-around, I'm well aware, but that's exactly what they are. A work-around.

**Comment by sgsunder** [comment]
This feels like it would add way more trouble than it's worth. You would need to define escape sequences for searching by tags, for instance.

Beyond the fact that spaces look better aesthetically than underscores, dots, etc., can you give any justification as to why this would be worth the effort?

**Comment by GlassedSilver** [comment]
Brackets always worked pretty well for searching strings in any other scenario.

And well, I think esthetics are quite important and as far as I can tell certainly a goal of this project.

Do we really need Gravatar instead of just uploading a picture manually? Sure, might be easy drop-in code, but you know, it's not like esthetics are unimportant. I could elaborate on that for a long time, but in the end it's up to those who write the code and have to deal with the manhours. I'm well aware of that.

**Comment by sgsunder** [comment]
I think that if someone make a PR with this feature without forcing awkward search syntax or hindering the usability of those who don't need whitespace in tags, that would be interesting. Beyond that, I don't think that any of the regular contributors would be interested in taking this on themselves.

**Comment by GlassedSilver** [comment]
How are brackets awkward? And if you don't want to use spaces you can keep using underscores can't you?

**Comment by neobooru** [comment]
I could see why you wouldn't want to use underscores as a replacement for spaces, but I can't think of a way to make searching not awkward.
Let's say that I want to search for the tags `neo` and `rwby`, currently I do that with `neo rwby`. You suggested using brackets, do you mean like this `{neo} {rwby}`?

Furthermore if we were to use an escape character we'd need to make that opt-in, since everyone is used to just using spaces, and this then leads to two different 'lifestyles' we'd need to support in the code.

That said, it would probably be possible/acceptable to hide the underscores in the fronted (like other  booru's do), this would make things prettier to look at, while not changing any functionality.

**Comment by GlassedSilver** [comment]
> I could see why you wouldn't want to use underscores as a replacement for spaces, but I can't think of a way to make searching not awkward.
> Let's say that I want to search for the tags `neo` and `rwby`, currently I do that with `neo rwby`. You suggested using brackets, do you mean like this `{neo} {rwby}`?
> 
> Furthermore if we were to use an escape character we'd need to make that opt-in, since everyone is used to just using spaces, and this then leads to two different 'lifestyles' we'd need to support in the code.
> 
> That said, it would probably be possible/acceptable to hide the underscores in the fronted (like other booru's do in the tag overview etc), this would make things prettier to look at, while not changing any functionality.

Sounds wonderful!

**Comment by sgsunder** [comment]
I think that a pure client side solution, a Boolean flag that is stored in cookies and makes underscores in tags display as spaces, would be a good enhancement. I'm a bit busy to work on this myself but I can review a PR
