### ISSUE TITLE
Bug: Client does not send auth tokens when calling GET /api/tag-categories

### ISSUE THREAD

**Issue by Metal-Mighty** [rr-/szurubooru#262]
Hi there,

I'm running an updated szurubooru instance and the tags aren't displayed in the color linked to their category, but in the default blue color. 
However, if I go to the tag categories and save the changes again (without changing anything), tags will have their proper color, until I reload the page. Navigating through the booru won't break the colors until the page is completely reloaded again.

**Comment by neobooru** [comment]
Could you open the developer tools and then reload the page. Does the console contain any red lines with something like '403 Forbidden /api/tag-categories'?

**Comment by Metal-Mighty** [comment]
I do have two errors when I load the page 
![image](https://user-images.githubusercontent.com/5247527/58430518-ecab7a00-80a9-11e9-87be-db44dcf9d193.png)

I usually use Firefox and had checked it but they don't color the line for 403 error codes, they only display the status at the end of the line, so I didn't notice it...

**Comment by neobooru** [comment]
I also saw this issue on my install a few days ago, but I just assumed I did something wrong. This is probably because you only allow signed-in users to view the tags-categories (?), and the client doesn't send the Auth token with the request. I might look into this sometime, but for a temporary workaround you can set the `tag_categories:list` privilege like this in config.yml (or config.yml.dist if you have no config.yml)

```yaml
'tag_categories:list': anonymous
```

**Comment by Metal-Mighty** [comment]
Ah, that was the cause indeed ! I switched the privilege to anonymous and it's now working.
This instance is a private one used to host my own pictures and as a PoC for a future public instance, and therefore switched any anonymous privilege to either regular or above.

Thank you for the help, I'll leave the issue open in case you want to keep track of it for a future fix.
