### ISSUE TITLE
Feature request: Import post from DeviantArt/Booru/Pixiv page

### ISSUE THREAD

**Issue by neobooru** [rr-/szurubooru#273]
Instead of pasting a link to the direct image you could just paste a DeviantArt/Booru/Pixiv link and the client would automatically find the hq-image link. In the future this could be extended to also import (existing) tags (if reasonably possible in the codebase).
This would require website specific code for e.g. DeviantArt/Pixiv/Booru-likes/Zerochan/Twitter/etc but it wouldn't be unrealistic to support the big websites.

I was going to make a cli-tool for this, but if others would be interested in this feature as well I could just add it to szurubooru (probably client-side).

**Comment by sgsunder** [comment]
I like the idea better as a CLI tool. I've wanted to make a tool similar to this idea for a while now, so I would be willing to contribute if you make a repository for this.

The reason I don't want to incorporate it into this project is because I want to avoid feature creep, as well as sticking to a Unix-philosophy approach. I'd rather see szurubooru focus on being a simple imageboard with a powerful API, and have external software interface with it for non-imageboard tasks.

That being said, I would like to add links in the README to repositories/software that are specifically designed to interface or enhance szurubooru, so that new users can expand their functionality as they see fit.

**Comment by rr-** [comment]
I met this problem in the past and I approached it in two big ways.

1. I made crawlers for each site (pixiv, gelbooru, safebooru etc.) + a CLI uploader with interactive tagging. This worked all right, especially when I downloaded images by tag rather than individual pictures, but was cumbersome to tag everything, and this only worked for me (because I had these tools) whereas other people still had poor experience in this regard.

2. I just uploaded direct links. Then a special szurubooru user, a bot, pulled newly uploaded images and searched for them on IQDB. For each supported website that IQDB linked, it downloaded the tags and set the image safety if applicable. There was some mechanism to deal with differences in tagging system between boorus and everything. But it was very, very cumbersome to maintain it. Eventually we just adopted gelbooru's tags.

Over time, our small community of a few people grew so indifferent about tags that we decided to pull the plug for the mentioned autotagging bot, and no users tag any posts manually… and it's okay.

I agree with @sgsunder that this is a very complex feature and it's best to keep code related to any third party services out of core szurubooru.

**Comment by neobooru** [comment]
Alright, thanks for chiming in on this issue.
Both solutions you pointed out sound valid, but I can also understand all the issues that inevitably would show up.

I started working on a basic chrome extension which when clicked on would grab the image from the currently active page (or maybe a right click context menu with something like "Import this image in szurubooru").
