### ISSUE TITLE
Feature request: Sidecar .txt for tagging uploads

### ISSUE THREAD

**Issue by HC1337** [rr-/szurubooru#276]
A very useful feature in the Booru Mass Uploader userscript is the Sidecar .txt that allows you to pick a text file with tags together with your uploaded image for mass tagging, it allows for easy exporting and importing of Hydrus images which supports sidecar files with line-separated tags.
Sidecar files could be either manually selected or linked with their respective images by their filenames, so File1.jpg automatically takes its tags from File1.txt.

I think this would be a massive boost in usability, maybe I didn't look hard enough but I couldn't find an easy way to import an already tagged library to szurubooru and this seems like the cleanest way to do it, it doesn't get in the way and doesn't accidentally tag things by inferring it from the filenames for example.

**Comment by sgsunder** [comment]
I'm going to give the same answer to this as I gave to #273. I don't want to feature creep by adding a whole bunch of tangentially related niche features on top of the core functionality of being an imageboard. There is a capable and [well-documented](https://github.com/rr-/szurubooru/blob/master/doc/API.md) API, so that users can script and automate stuff like mass-importing, or developing interfaces with other applications such as Hydrus.

I'm not too familiar with Hydrus personally, but this seems to be something that could easily be done via a client-side script, or a Hydrus plugin (if Hydrus supports plugins). And looking at https://github.com/Seedmanc/Booru-mass-uploader it might even be a good idea to make a PR and have them support szurubooru.
