### ISSUE TITLE
404 on all images after deleting local git copy of szurubooru

### ISSUE THREAD

**Issue by Metal-Mighty** [rr-/szurubooru#278]
Hi !

So I am feeling a little dumb there: I had a git error which prevented me from pulling the last version of Szurubooru, and instead of figuring out the source I just deleted the local folder and pulled it again. Not my best move.

I had only saved my modified docker-compose file, so I filled in the config.yml and .env files again by memory and booted it up again. All the data was mounted on Docker volumes (`index` for ES, `data` for the API + client, and `sql` for PG) that I kept and reused with the new instance in order to keep everything.

The new instance did recover all the data (posts, users, tags, and so on), but all the images, thumbs and source images alike, cannot be found.
I browsed to my /data folder and all images are present, but the links generated by Szuru are wrong, e.g. post 2455 which was called `2455_928ede6b3e9cb1f7.png` on disk, and Szuru now tries to access it with the name `2455_58bb5adbf0b96dc5.png`. New posts are correctly displayed.

What would be the cause of that change in filenames, and is it possible to recover the links to the existing pictures?
I am also curious to know how the said names are generated, since they don't seem to be stored in the PG database.

**Comment by sgsunder** [comment]
Sorry for the late reply.

The filenames are generated based off the value used for 'secret' in your `config.yaml` file. 

The relevant code which sets the filenames is in [`func/posts.py` - Lines 88 to 132](https://github.com/rr-/szurubooru/blob/83442b497795616e33e81e6938c59fa4c2482027/server/szurubooru/func/posts.py#L88-L132)

You're not the first person to ask about this, so I quickly made a function in the `szuru-admin` script to fix the filenames due to a changed secret. If you are running through docker, run

```shell
docker-compose exec api ./szuru-admin --reset-filenames
```

This should fix *all* the filenames to be correct.

**Comment by Metal-Mighty** [comment]
No problem !

I actually thought about the secret parameter having some kind of influence since I forgot what it's value was before deleting the file, and I changed it on the new instance. 
I knew it was for password salting, so I had to update my password, but it is not indicated that it is also used for the filenames. It might be worth mentioning it in the comment above the value ?

And thank you very much for the script, worked like a charm!
