### ISSUE TITLE
Helpdesk: Clarification on using a different domain for hosting static files

### ISSUE THREAD

**Issue by TiredSysOp** [rr-/szurubooru#299]
>Using a seperate domain to host static files (image content)
>
>If you want to host your website on, (http://example.com/) but want to serve the images on a different domain, (http://static.example.com/) then you can run the backend container with an additional environment variable DATA_URL=http://static.example.com/. Make sure that this additional host has access contents to the /data volume mounted in the backend.

Could someone clarify what "Make sure that this additional host has access contents to the /data volume mounted in the backend." means. I assume it means that there are two instances of szurubooru running using the same database and data. Where one is polled for the data using the data url with a different sub-domain.

Regards

**Comment by noirscape** [comment]
Basically, it's useful if you'd rather have images and thumbnails served in a different way.

It's mainly useful once you use szurubooru's docker container as a reverse proxy in front of a local nginx install, since at that point you're not stressing the server part with serving the images and it's just tasked with handling the API requests and you can let nginx do that instead.

If you want to serve the data folder on the domain `static.example.com`, and you have szurubooru already set up to use `/srv/szuru/data` as your data folder, then you'd have to point nginx's configuration file for `static.example.com` to use `/srv/szuru/data` as the webroot and use `DATA_URL=http://static.example.com/` in your config.

This is only really useful once you start hosting a public instance that is going to have multiple people accessing it at the same time, otherwise the server part can handle serving the images just fine.

**Comment by TiredSysOp** [comment]
Nginx is configured correctly, I'm still having trouble with szurubooru. Where and what needs to be changed to get szurubooru to serve data from the static site. As I've tried adding DATA_URL=http://static.website.com/ to .env and the backend server config, when added to the backend it throws an error about a missing colon, when using the configuration section for setup outside of docker it get ignored.

**Comment by TiredSysOp** [comment]
Looks broken to me, dirty workaround in nginx

		location ^~ /data/generated-thumbnails {
			return 301 http://static.example.com$request_uri$is_args$args;
		}
		
		location ^~ /data/posts {
			return 301 http://.example.com$request_uri$is_args$args;
		}

server {
	server_name static.example.com;
	root /var/local/szurubooru;
	location / {
		try_files $uri $uri/ =404;
		autoindex on;
    }
}

server {
	listen                  443 ssl;
	server_name static.example.com;
	root /var/local/szurubooru;
	location / {
		try_files $uri $uri/ =404;
		autoindex on;
    }

  ssl_certificate         /etc/letsencrypt/live/example.com/cert.pem;
  ssl_certificate_key     /etc/letsencrypt/live/example.com/privkey.pem;
}

**Comment by TiredSysOp** [comment]
Above is no good, will give it another go at some point

**Comment by sgsunder** [comment]
Sorry it took me so long to get back to you.

I'm not really sure about the issue you're facing. The original intent of the 'DATA_URL' parameter is to allow for the serving of the static content (the images) on a separate domain. (i.e. if you're using a CDN).

To do this, you're really expected to fork the project and modify `/client/nginx.conf.docker`, because this is a pretty niche use case.

**Comment by TiredSysOp** [comment]
I assume I change this value:
        location /data/ {
            rewrite **^/data/(.*) /$1 break;**

**Comment by TiredSysOp** [comment]
Right that's perfect, The problem I originally faced was that posts weren't embedding in discord, but they worked if they were served directly by nginx over an insecure connection. Now it works, google is being odd with it's mixed content warning for "insecure videos" but that's beyond the scope of my problem. Thanks again

**Comment by TiredSysOp** [comment]
What has google done. Chrome upgrades the connection to https and the rewrite rule downgrades it as I've set it to http rather than use scheme. Oh well, least it's something to learn from. Cheers!
