### ISSUE TITLE
URL Preview/Thumbnails and general information

### ISSUE THREAD

**Issue by Andre19926** [rr-/szurubooru#308]
Greetings,
I have a question regarding posts made on the booru.
Is it possible to enable URL previews?

What I mean is the image being displayed when posting a link.
e.g: www.examplebooru.test/post/156/

So far there is no preview of any images, let alone a general page information that is given when posting any link such as "Website Name - Here" with info given.
Is it even possible to change a posts name?

Thanks in advance!

**Comment by sgsunder** [comment]
I don't think this is possible in szurubooru, because it is implemented as a single page application. So a service that supports URL previews (Facebook, Discord, etc.) would have to load and execute javascript as if it were emulating a web browser, in order to get detailed information about a post URL.
