### ISSUE TITLE
Use exif metedata to rotate images

### ISSUE THREAD

**Issue by yeniklas** [rr-/szurubooru#311]
I've noticed that many of my photos are turned the wrong way around(I use szurubooru for managing photos).

Photos taken in portrait will be turned sideways, however if I click the "download" button the browser turns the image the right way.

You think this is something that is fixable? I'm not sure if this is too far from the intended use case but I'm throwing out the question at least.

**Comment by sgsunder** [comment]
Seems related to this discussion: https://stackoverflow.com/a/42428659/13027787

Makes it sound like primarily a browser-based issue. We might be able to hardcode the rotation in the image once it's uploaded, but I'm not sure if that's a good idea (might be a lossy transform)

**Comment by yeniklas** [comment]
It seems to work as expected in the browser when it opens the photo file only(the download button)
So whatever the browser does to handle this I guess should be possible in Szurubooru itself without actually changing the original files?

But the thumbnails would need to be generated in a rotated fashion I guess.

**Comment by yeniklas** [comment]
I see, I was not aware of this browser problem. I think if we need to do conversions in Szurubooru itself it won't be worth it. In that case it's probably better to just preprocess the images before upload.

Or maybe it could be an option during upload to rotate the images based on exif.

**Comment by TangentFoxy** [comment]
> an option during upload to rotate the images based on exif

This gets my vote! Would be nice.

**Comment by noirscape** [comment]
If that's going to be the way, I would really prefer for that to be a configuration option. Right now, one of the reasons I like szurubooru is specifically _because_ it's not manipulating or downscaling the images outside of generating the thumbnail.

If the source images are going to be modified, that would be a major negative for my usecase of szurubooru.

**Comment by yeniklas** [comment]
I agree, it should be an option during upload but should not change current behaviour.

**Comment by noirscape** [comment]
> during upload

I suppose I wasn't clear, I would like this to be an _administrative_ permission, if this were ever to be implemented.

**Comment by yeniklas** [comment]
I see. Yeah I think it would make sense to allow utilizing this feature through permissions in a similar way as with the youtube-dl feature.

**Comment by sgsunder** [comment]
I would not do any messing around with the image on server-side at all (even as an option).

The CSS property `image-orientation: from-image` would do exactly what this issue is asking for, however [browser support is not really there yet](https://caniuse.com/#feat=css-image-orientation) (basically only Firefox for now, however Chrome Canary also has it implemented so it's likely to come to mainline Chrome very soon.)

I will author and test (in Firefox) a commit with this CSS property soon.

We could write some client-side JS to do it manually and get more browsers to support it, but I'm not sure it's worth the effort - other browsers will eventually support the CSS option as well. If someone really wants a JS implementation, I'll be willing to review a PR.

See https://stackoverflow.com/a/36593389/13027787 for more details

**Comment by thegreatestminer** [comment]
`image-orientation` is now widely supported by Edge, Firefox, Chrome, and Opera.
