### ISSUE TITLE
BUG: Youtube videos scraped in low quality.

### ISSUE THREAD

**Issue by WNSwins** [rr-/szurubooru#331]
Thank you for this awesome booru software it’s quickly becoming the most used thing on my unraid server. 

  I am running Szurubooru on my unraid server in a Docker from unraids CA repo.  The docker is maintained by FoxXMD on the unraid forums.  The docker is running Alpine Linux v3.12.

  When I use the upload page to scrape youtube videos they are ripped in low quality and not HD.

   This is behavior that youtube-dl does if ffmpeg is not installed.  Youtube splits most HD videos into two streams, one for audio and one for video.  If you run youtube-dl from terminal and ffmpeg is not installed it will grab the highest bitrate stream that includes video and audio. That seems to be the behavior of Szurubooru.  

  If ffmpeg is installed then when you run youtube-dl <url> from terminal with no arguments youtube-dl will grab the highest bitrate video stream and if it does not contain audio it will then grab the highest audio stream then automagicly use ffmpeg to merge them and spit out an HD video file then delete the original downloaded streams.  

  I tried SSH’ing into the unraid server and diving into the szurubooru server docker container to install ffmpeg but, apk shows ffmpeg is installed.  Running youtube-dl from inside the container works as desired and automagicly uses ffmpeg to spit out an HD video file.  So youtube-dl and ffmpeg do work in the container.

  Manually uploading HD files created in this way works fine.  These files are able to be viewed in Szurubooru’s video player.

  I am not sure if this is a bug with the docker or with Szurubooru itself.  The way I see it the issue might be either:

1. Something is wrong with the docker.  I don’t know enough about dockers to rule out a permission or other issue.  

2. Szurubooru is running youtube-dl with arguments that prevent the use of ffmpeg. I tried looking through the code to see what command was being passed to youtube-dl when a youtube url is put it. But I have not yet found that part of the code. 

3. Ffmpeg is being called from a location where it cannot run.  Ffmpeg needs to be able to create a new file and delete the old files it used to create the new file from.  I believe that if ffmpeg cannot do these things then it will fail and youtube-dl will fall back to downloading a single stream.

**Comment by WNSwins** [comment]
Ok I believe I found the cause of the issue.  It looks like Szurubooru is passing the url to youtube-dl with the  best tag.  

Omitting the best argument when passing the url to youtube-dl should fix the issue. 

szurubooru/server/szurubooru/func/net.py  (line 40)
`options = {
        "ignoreerrors": False,
        "format": "best[ext=webm]/best[ext=mp4]/best[ext=flv]",`

  You used to need to use best to get youtube-dl to pull down the well, best quality video. Now with this tag youtube-dl selects 1 stream containing the best audio and video, usually an SD stream.  

  I do not have the time or setup at the moment to fork it for testing but I may in a week or so if no one else has.

**Comment by sgsunder** [comment]
[Quick link for line in question](https://github.com/rr-/szurubooru/blob/800a79f95f667fb03fc705835271a76a8d0a168c/server/szurubooru/func/net.py#L42)

I recall running into this issue when I was authoring this feature. As far as I can tell, the split-stream approach is not employed by many video streaming sites besides Youtube.

The problem is that the `best` flags optimize the video quality for non-youtube sites. Given that szurubooru is an image board, I chose to target optimal quality from video "gifs" on Gfycat, Twitter, Reddit, etc.

The ability to download full-length VODs from sites like Youtube was an ancillary benefit. I don't want to sacrifice quality of the primary use case for the sake of an ancillary use case.

However, you seem to be more knowledgeable about youtube-dl than I am, so if there's a way to get maximum quality from both youtube and gfycat/twitter/etc, let me know and I can make the improvement.

**Comment by WNSwins** [comment]
Sorry for the delay, I've been quite busy here.  I agree that we should not sacrifice quality for this feature, however I don't think we need to.  

Youtube-dl by default runs:
`--format bestvideo+bestaudio/best`
This means it tries to download the best stream with just video and combines it with the best audio only stream using ffmpeg.  If it cannot (e.g. the site does not work like YT or ffmpeg is not installed) then it falls back to using 
`--format best.`

Youtube-dl used to act differently and you had to pass the best flag(or bestvideo+bestaudio for YT like sites) to get the best quality video from it.  This is the default behavior now.  

So to keep your file preferences for other sites we could change the line to:
`"format": "bestvideo+bestaudio/best[ext=webm]/best[ext=mp4]/best[ext=flv]",`
or 
`"format": "bestvideo+bestaudio/best[ext=webm]/best[ext=mp4]/best[ext=flv]/best",`
to also scrape any other video file types if the preferred ones are not found.  

I'm realizing now that your intention with the format line might be to pull down the highest quality file of type .webm, .mp4, or .flv. if that is the case that is not what this line is doing.
The line:
`"format": "best[ext=webm]/best[ext=mp4]/best[ext=flv]"`
tells youtube-dl to try to download the highest quality webm and if _none_ are found then try mp4 then flv.  Meaning if a site has a video that is 480p in webm but 1080p in mp4 youtube-dl will download the webm file because it is preferring that format.  

If the intention is to make sure videos are in one of these formats then you might be better served by just having ffmpeg transcode the highest quality videos to a preferred format.  You can do this from youtube-dl with:
`--recode-video FILETYPE`
In this case we could just replace the format line with recode. 
e.g. change
`"format": "best[ext=webm]/best[ext=mp4]/best[ext=flv]",`
to 
`"recode-video": "[ext=webm]",`
to transcode all videos to webm for instance(it won't transcode it if the file is already webm).  Syntax might not be quite right.  I usually run these things from the terminal.

Let me know your thoughts, I'm happy to help.

**Comment by sgsunder** [comment]
I don't want the downloader to trigger the ffmpeg encoding sequence at any point because it is very CPU intensive and could cripple a webserver, especially if it's deployed on something like an ultra-lightweight cloud platform.

So if there's a way to restrict `"recode-video": "[ext=webm]"` and `"format": "bestvideo+bestaudio"` to only perform lossless remuxes instead of transcodes (effectively limiting ffmpeg to only using `-c:v copy` and `-c:a copy` as its codec flags), that would be good. Otherwise, I don't want for someone to accidentally DDOS the server because they tried fetching a DivX file instead of an MP4 🙃

> Meaning if a site has a video that is 480p in webm but 1080p in mp4 youtube-dl will download the webm file because it is preferring that format

Ideally, we would be able to remove some of youtube-dl's abstraction so that we can write a bit of logic ourselves, selecting an optimal filetype and ensuring that split stream websites like youtube can be muxed into a single file without needing a transcode. I have no idea how to go about doing that though.

**Comment by FlipperLP** [comment]
Well in that case, an option to enable it in the config, would be handy.

**Comment by sgsunder** [comment]
Tweaked the ffmpeg logic a bit in c7461c7f65cfc42e6f33970c47f1030ed2c3a184 so hopefully it works better with youtube.

> Well in that case, an option to enable it in the config, would be handy.

Having an option to do the muxing seems to be a lot of effort for:
- A very narrow use case (So far, I only noticed that youtube has their video and audio streams split, every other website works fine)
- Outside the primary use of szurubooru. While it can support large videos, szurubooru is primarily meant to be an image board.
- An issue that can be circumvented by the end user, by manually downloading from youtube and pushing the files
