### ISSUE TITLE
Can this handle large datasets?

### ISSUE THREAD

**Issue by kemono-bugs** [rr-/szurubooru#358]
I'm considering using this booru engine for a dataset that is about 5TB large, with about ~2 million files as of the writing of this post (rough estimate, probably more) 
[Back in 2018, you mentioned Szurubooru might have issues with something like this,](https://github.com/rr-/szurubooru/issues/200#issuecomment-422660370) so I want to know if this is still the case.

**Comment by sgsunder** [comment]
If each individual file is small (< 1GB) then I don't anticipate any major problems for you. I can't really make any promises, of course, since we only have ran with a couple dozen GB on our instances.

It gets tricky (yet still doable) for large single files (> 1GB). When performing uploads on files, the REST app will have the entire stored in RAM until the data is validated and written. So you might need a lot of RAM to make something like that work.

**Comment by kemono-bugs** [comment]
Hmm, alright. Also, correct me if I'm reading the [code for this](https://github.com/rr-/szurubooru/blob/master/server/szurubooru/func/posts.py#L404) wrong, but are the images being stored in the database?

**Comment by neobooru** [comment]
> Hmm, alright. Also, correct me if I'm reading the [code for this](https://github.com/rr-/szurubooru/blob/master/server/szurubooru/func/posts.py#L404) wrong, but are the images being stored in the database? If so, would a very large file slow it down?

Images are stored as jpg/png/etc in the `public/data/posts` folder, though you can always symlink it to another folder. (Or change the docker parameters if you use that).

I don't think you'll get acceptable performance with a dataset that large. My 'production' instance is definitely slower than any dev instances I spin up. This might be due to the different hardware/structure though.
I think the queries that the backend executes aren't really optimized for large collections (with many tags), though I currently can't provide any proof for that. Or maybe I just have to change some parameters in my postgresql instance.
