### ISSUE TITLE
Feedback / Things to improve

### ISSUE THREAD

**Issue by 59716123** [rr-/szurubooru#362]
Hello everyone,

first of all, I wanted to thank you for this. I installed szurubooru on a Raspberry Pi 3, and it works (mostly) flawless.
I'm using this as a backup booru just for myself, so the Pi should handle the workload just fine.
Here's some feedback I collected while working with it:

- **Build**  
I haven't worked with docker before, but building the files and running docker was easy.  
I've stumbled into permission errors when running szurubooru, but with [this post](https://github.com/rr-/szurubooru/issues/216#issuecomment-450188704) I was able to fix it. 

- **Uploading**
I've used [Grabber](https://github.com/Bionus/imgbrd-grabber) to download files to my PC and the [updated script](https://github.com/Bionus/imgbrd-grabber/issues/2086#issuecomment-710006672) to upload them to my Pi. I've added some debugging into it, so here are some issues:
1. Some of the bigger files (>30MB) returned an error code 504: "_Failed to connect to szurubooru REST API_". 
The files were still processed correctly. I think this is a limitation from the raspberry pi.
2. Some Tags, mainly ones containing a ? or a ! returned error code 400: "_TagAlreadyExistsError_" -> "_One of names is already used by another tag_.".
I've ignored this, since the tag was added anyway. 
3. Some .mp4's returned error code 400: '_InvalidPostContentError_' -> "_Unhandled file type: 'application/octet-stream'_"  
The files were not added to the booru.
I've used ffmpeg to create a new container ( -c:a copy and -c:v copy) and uploaded it again, then it worked.

- **Duplicates**
Since I've downloaded everything with grabber and uploaded it with the provided script, I couldn't check for similar images.
I've seen that real duplicates get filtered out, but the same image with a different hash does not.
I then used [DuplicateImageFinder](https://github.com/yastrov/DuplicateImageFinder) to sort images by similarity and merged them manually. Very tedious, here's hope to have something in the website that show me (the admin) visually similar images to merge. I think something like this already exists, but only on manual uploads. Maybe this can be expanded further to show similarity on the whole dataset.

- **Pools**
I really like the idea of pools (haven't used them on other boorus yet). Will this be a feature to e.g. include doujinshi in a useful way?
Would be really cool if I can just e.g. tag the cover page with all the relevant tags and then click on a button to read the doujinshi. (similar to "read book" on sankakucomplex)
Would also be cool to have the Cover of the doujinshi on the pools page similar to [e.g. Danbooru](https://danbooru.donmai.us/pools/gallery)

- **Hide posts**
Is there a way to hide posts yet? For example, I've uploaded a doujinshi and don't want any of the pages except the coverpage to show up in the search results. 

- **Swap ID's**
Is it possible to Swap ID's? I've made the mistake of not using order:id when downloading files, so my sorting is all messed up. I'd really like to manually sort/swap ID's. Odd request, I know.

- **sort:random**
I've used sort:random for a while and there are two things I noticed:
1. When viewing a post, using the next/prev buttons it will ignore the sorting. Expected behavior is that it respects the search terms.
2. Refreshing the page / pressing F5 does not change the random order. It's useful when you go back from the post to the previous search results, but I'd like to have a way to have another random search result.

- **next/previous post**
I'd like to have the history off when using next/prev. So when I press "back", I return to the search results. I can already use left/right arrow to navigate to the next/previous post, so using "back" to return to the seach result is a nice to have feature.

  
   

  
All in all I'd like to thank everyone again for providing this great software.
cheers.

**Comment by noirscape** [comment]
Uploading:

1. This sounds like something being wrong in your reverse proxy. Check your nginx/apache/caddy/whatever your server is setup with for that I guess. If you're not using a reverse proxy, then it's a bug.
2. That seems like the fault of the Grabber script you're using. It uses bad string interpolation to update tag categories and the like.
3. This sounds like a bad video file. Happens sometimes, it causes mimetype detection to fail. As you said, re-encoding the file in ffmpeg usually works.

Duplicates:

If you use the web uploader, there's a fairly decent dupe detection system, which halts if an image hits a certain treshold (I'm not sure from the top which is which) and then either lets you remove the image from the uploader/make it a parent/copy tags/do nothing/parent + copy tags. You _can_ call it from the API too, just check the docs. This seems like something the grabber script simply doesn't implement.

A frontend for the dupe detection for any url (without necessarily uploading) could be desirable as a view, as well as a link to that on the post view that does the dupe detection for that post. Personally, I don't have use for it, but I can see this being useful.

Pools:

Yeah that's basically the idea. Lists of posts in a sequence (sequenceless posts grouped together are called sets, which szuru doesn't have) is the idea behind booru pools. I'll admit to not having tested this feature yet in szurubooru, but you have that part right.

Hide posts:

Not currently in afaik. Could be useful, but would need a token to explicitly show hidden posts (or to only show hidden posts).

Swap IDs:

Not feasible due to the way the DB is laid out. Use pools instead, it's what they're meant for.

sort:random/next previous:

I don't know enough about this to comment on it.

**Comment by sgsunder** [comment]
> Some of the bigger files (>30MB) returned an error code 504: "Failed to connect to szurubooru REST API".
The files were still processed correctly. I think this is a limitation from the raspberry pi.

Possibly an out of memory error on the Pi? Were there any logs?

> Duplicates

There's already a documented API endpoint for the reverse image search. You could modify your script to use this instead of performing it with an external application: https://github.com/rr-/szurubooru/blob/master/doc/API.md#reverse-image-search

> sort:random

A lot of these issues are because the random sort is unable to be cached effectively without using some kind of session token. Not sure if there's a simple way to fix this...
