### ISSUE TITLE
Questions: Pools and Discussion

### ISSUE THREAD

**Issue by SkandhaR** [rr-/szurubooru#384]
2 Questions:
1. What is the intended use of a Pool? 
Don't think I've ever interacted with pools on other booru's so I'm unsure. To me it feels similar to a regular tag. I've just been tagging CG Sets and Artbooks with a distinct tag.  I also noticed that pool membership is not displayed on individual posts.
2. Is it ok to be spamming the issues section with non-issue discussion? (Like this post)

**Comment by 404Fox** [comment]
When it comes to other sites, pools offer image ordering, can have a searchable title with whitespaces, and pool browsing similar to galleries.
The current implementation does not have these features though. See #380 
Discussion here is probably OK, since there isn't anywhere else to discuss the booru that I know of.
