### ISSUE TITLE
Request + Questions

### ISSUE THREAD

**Issue by SkandhaR** [rr-/szurubooru#392]
Request: Consider enabling the Discussions section for this repo. See below for instructions.
https://docs.github.com/en/discussions/quickstart

Questions:

- Is there a way to search for posts without a source? I can't seem to figure it out. Looked through the documentation a bit, maybe I'm blind. I'm able to search for things that do have sources, so I assume this is also possible.
- Is there a way to control what level of access a user needs in order to see posts with certain tags or with a certain safety level? 
Similar to how you can control to things like Pools, Tagging, and Registration.
- Having issues with the "Help" section of the site. I brought down my docker containers, went to /szuru/client/html and edited help_about.tpl.  When the containers were back online, I didn't see this change. I checked and the file is still the same as before.
A simple `<p>test</p>` as a test.

**Comment by noirscape** [comment]
> * Is there a way to search for posts without a source? I can't seem to figure it out. Looked through the documentation a bit, maybe I'm blind. I'm able to search for things that do have sources, so I assume this is also possible.

No special key of the sort exists at the moment.

>Is there a way to control what level of access a user needs in order to see posts with certain tags or with a certain safety level? Similar to how you can control to things like Pools, Tagging, and Registration. 

Not possible at the moment.

> Having issues with the "Help" section of the site. I brought down my docker containers, went to /szuru/client/html and edited help_about.tpl. When the containers were back online, I didn't see this change. I checked and the file is still the same as before. A simple <p>test</p> as a test.

That's not how docker works. If you want your changes to the help page to show up, you need to bring down the containers, edit them in the source code folder and rebuild the container. Otherwise, your changes are ephemeral; when the container is removed, your changes will be as well.

A quick reference to be clear:

* `docker-compose down` stops and also **removes** all old containers. Changes you made on the containers' filesystem are lost.
* `docker-compose stop` just stops all old containers. Changes you made on the containers' filesystem are kept.
* `docker-compose up` starts up and creates missing containers according to `docker-compose.yml`. It also *replaces* any outdated containers if a new one has been pulled in since, meaning that if you pull in new containers, your changes could be lost.
* `docker-compose start` starts up existing containers. It doesn't replace or create outdated/missing containers.

**Comment by SkandhaR** [comment]
Looks like I got that far with docker. Here was my exact process:
- Go the szuru/ and do `docker-compose down `
- Then `docker container ls` to make sure they got destroyed.
- Edited the help_about.tpl.
- Did `docker-compose up -d`


The change didn’t carry over into the newly generated containers. 

Chances are I’m doing something wrong still. I only have 1 szuru/ folder so I’m pretty sure I’m in the correct folder.

**Comment by noirscape** [comment]
You need to rebuild the client container. Run `docker build -t szurubooru/client:latest .` in the client folder (dont forget the dot).

Also expect to have to do that each time the repository updates.

**Comment by SkandhaR** [comment]
Docker lessons with noirscape. Thanks for the help, that worked!

I was unsure of the relationship between the image pulled from DockerHub and the folder pulled from this repo. I have a better understanding of what is going on now.

**Comment by sgsunder** [comment]
> Request: Consider enabling the Discussions section for this repo. See below for instructions.
https://docs.github.com/en/discussions/quickstart

@rr- I don't have access to do this, can you do it?

I would also ask that we add more collaborators to this project, because I have been unable to respond to issues in a timely manner for a while now. I noticed that @neobooru has been contributing quite a bit, maybe they would be interested?

**Comment by rr-** [comment]
@sgsunder I enabled discussions and have invited @neobooru :)  I agree on more collaborators.

**Comment by noirscape** [comment]
Would discussions supersede the current use of the helpdesk label?

Sorry, I'm none too familiar with the discussions feature.

**Comment by sgsunder** [comment]
I think that would be a good idea. Limit the issues section to bugs only
