### ISSUE TITLE
Update client builder image to Node.js LTS

### ISSUE THREAD

**Issue by neobooru** [rr-/szurubooru#412]
The current Docker builder image is based on `node:9` which is rather old at this point. During image creation it throws the following warning:
```
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
```

Arguably we could just stay on Node.js 9 because nothing is broken (yet?), however development (at least for me) happens on Node.js LTS so it might be better to also use that in our Docker images.

Thoughts?

**Comment by sgsunder** [comment]
I think it's safe to upgrade it to the latest. It's not a runtime dependency so as long as the build script runs, it shouldn't matter what version we use.

**Comment by noirscape** [comment]
Assuming that it works, then yeah go ahead.

AFAIK the only image that absolutely needs to be pinned is the database since upgrading a postgresql datbase over docker is a massive PITA to the point where the "official" docker approach is to dump the entire thing and reimport the database in a new container rather than bothering with the mess that is pg_upgrade.
