### ISSUE TITLE
Install SSL Cert on Docker Szuru image?

### ISSUE THREAD

**Issue by UsualVII** [rr-/szurubooru#511]
I've made it, a really clean install, but I have this Let's Encypt! certificate with ca_bundle.crt, certificate.crt and private.key, and I was wondering how to install it on my VPS IP (i've then fowarded that IP via A and C Name in a domain name)

Running on Ubuntu with Docker

**Comment by neobooru** [comment]
The easiest way to get this is to use a reverse proxy. There are a bazillion different ways to achieve this. [This page (point 3 & 4)](https://github.com/rr-/szurubooru/blob/master/doc/INSTALL.md#additional-features) show you some possible configurations. Those however do not show how to add SSL/TLS, so if you have no experience with NGINX it is kinda tricky to get working.

If you tell me what you want your setup to look like then I can probably give you an example config. For example which http server you want to use, and if you want your site to be accessible from either `http://example.com`, or `http://szuru.example.com`, or `http://example.com/szuru`.

**Comment by xShoalKing** [comment]
just https://example.com/

**Comment by skybldev** [comment]
If this issue is still up in the air, here's what you can do using NGINX:

1. Create a config for your site. Don't worry about the cert yet. Just follow the config example from the bottom of this page: https://github.com/rr-/szurubooru/blob/master/doc/INSTALL.md and put it in `/etc/nginx/sites-available`
2. Run `sudo certbot --nginx`. It will present you with a list of domains that it can activate HTTPS for. Choose the appropriate one, and let it do its thing. When it's done, you can go check on the config you just made and see its edits.
