### ISSUE TITLE
Any shell vulnerability?

### ISSUE THREAD

**Issue by xShoalKing** [rr-/szurubooru#514]
We're planning to getting started on something big, and before opening the "gates" to our community we would like to make sure there is no possible way of attacking us via an upload of a reverse shell in an image file (.jpg)

**Comment by skybldev** [comment]
As far as I've tested and read the code, there is no way to upload a shell script disguised as an image file because the software that decodes and processes the images (ffmpeg) serverside will return an error if the file isn't an actual image.

**Comment by neobooru** [comment]
Well, if we knew that there was a vulnerability then we'd have fixed it. I'd say the chances for a vulnerability in the image processing are slim because we are using well-known python libraries, which means that (generally speaking) many different devs have looked over that code. Additionally you should have szurubooru running in docker, which means that it is (mostly) isolated from your host system. And as always, create backups!

**Comment by xShoalKing** [comment]
Thanks for your answer, guess we’re ready! :)
