### ISSUE TITLE
coding a API POST request to upload image

### ISSUE THREAD

**Issue by modymp** [rr-/szurubooru#572]
### Discussed in https://github.com/rr-/szurubooru/discussions/570

<div type='discussions-op-text'>

<sup>Originally posted by **modymp** April  5, 2023</sup>
greetings!

I am trying to code a script that will help me post data to the Szurubooru instance. And the plan is convert this into an iOS/macOS Shortcut so I can upload images. 

> a beginner in Python or interpreting API doc and hence finding it hard to get this done. Any help appreciated!
- where-iam-struggling: I could not figure out how to "post" image data as per the API guidelines
- [ ] api: https://github.com/rr-/szurubooru/blob/master/doc/API.md#file-uploads
- [ ] api: https://github.com/rr-/szurubooru/blob/master/doc/API.md#creating-post

> what works: a GET works fine
```py
import requests
ENDPOINT = "https://booru/api"

get_headers = {
    'Content-Type': 'application/json',
    'Accept': 'application/json',
    "Authorization": "TOKEN LTRmOWUtOTAyNC0x",
}

get_response = requests.get(url=f"{ENDPOINT}/post/1", headers=get_headers, verify=False)
```

> failing: a POST to upload a file fails
```py
import requests

ENDPOINT = "https://booru/api"

authheader = {
'Authorization': 'TOKEN LTRmOWUtOTAyNC0x',
}

data17 = {
    "tags": "2process",
    "safety": "safe",
    "metadata": open("Downloads/bor/unknown.png", 'rb'),
}

post_response = requests.post(url=f"{ENDPOINT}/posts/", verify=False, headers=authheader, files=data17)
print(post_response.text)
```

As I was not certain of adhering to the API guidelines I did try to seek help on forums that are specific for [Python](https://discord.com/channels/267624335836053506/1092874897438556200) and on [Reddit](https://www.reddit.com/r/selfhosted/comments/12buj1f/code_for_creating_a_post_in_image_board_instance/?utm_source=share&utm_medium=web2x&context=3).. I could not make progress, so, I am trying here to check.. 

I tried to modify the code by reading a few articles & other GitHub projects, but I am sure I missing some thing. 
- https://blog.jetbridge.com/multipart-encoded-python-requests/ 
- https://stackoverflow.com/questions/9733638/how-to-post-json-data-with-python-requests
- https://github.com/reluce/szurubooru-toolkit/tree/main/src/szurubooru_toolkit 

thanks!</div>

**Comment by neobooru** [comment]
This works for me. Probably not the cleanest/best code, but it seems to work. You can also use the [pyszuru](https://github.com/sgsunder/python-szurubooru) library to create posts, though I didn't test it.

```py
import requests
import json

ENDPOINT = "https://booru/api"

headers = {
    "Accept": "application/json",
    "Authorization": "Token LTRmOWUtOTAyNC0x",
}

files = {
    "content": open("Downloads/bor/unknown.png", "rb"),
    "metadata": json.dumps(
        {
            "tags": ["2process"],
            "safety": "safe",
        }
    ),
}

post_response = requests.post(
    url=f"{ENDPOINT}/posts", verify=False, headers=headers, files=files
)

print(post_response.text)
```

**Comment by noirscape** [comment]
I've written a couple of API upload tools over the years - Here's a few comments of mine.

1. Make use of [request sessions](https://requests.readthedocs.io/en/latest/user/advanced/#session-objects) - very straightforward. They allow you to reuse parameters easily without needing to specify them over and over. Just set up a session object once and your authentication and `Accept` and `Content-Type` parameters will be taken care of. It also allows you to take full advantage of connection pooling, which can make repeated uploads considerably faster.
2. If you can, don't mix file uploads with metadata uploads. The `metadata` file is best treated as a second-class option IMO.
3. Relatedly, make use of the [temporary uploads API](https://github.com/rr-/szurubooru/blob/master/doc/API.md#uploading-temporary-file). This API just accepts the file you want to upload as long as it's named `content` and allows you a token you can use for other stuff. Consider this also very useful for combining it with reverse image search or for uploading large files.
4. When using files, consider using `contentToken` (use it with the file uploads API) and `contentURL` (allows you to make szurubooru fetch from a webresource instead - do note that by default there is no user agent for this unless you set one in `server.yaml`) instead, they can both be expressed using the default JSON format.

With that in mind, I would rewrite @neobooru's script as follows. I also made use of a context manager for the file since neo's script leaves open file handles.

```py
import requests

# conventional names for a session include session, s and r. i use session here. pick your poison.
session = requests.Session( 
    headers={
        "Accept": "application/json",
        "Authorization": "Token LTRmOWUtOTAyNC0x", # I strongly recommend putting this in a config file and just f-stringing the value in.
    },
)

API_URL = "https://booru/api"

# context manager means that the file handle will always be properly closed, even if something fails.
# some operating systems don't clean up loose file handles which can lead to OS weirdness.
with open("Downloads/bor/unknown.png", "rb") as uploadfile:
    # first we upload the file to temporary storage and get the token from the response
    temporary_data = session.post(f"{API_URL}/uploads", files={"content": uploadfile}).json()
    file_token = temporary_data["token"]

    # here you can use that token for anything else you want to do pre-upload, such as reverse image search.

    # next we upload the file for real
    # you can add your own parameters here - token and safety are the only required ones. 
    # setting content-type here explicitly means its added to the session headers
    post_data = session.post(f"{API_URL}/posts", json={"contentToken": file_token, "safety": "safe"}, headers={"Content-Type": "application/json"})

    print(post_data.json()) # finally we print the uploaded post data.
```

**Comment by modymp** [comment]
thank you @noirscape, appreciate the feedback and explanation! I have learned a lot in this exploration.   

1. session Object - cool! will explore it to understand it further 
2. metadata - understood. "second-class option" is this related to the API endpoint (szurubooru server)?  
3. temporary uploads - thank you for sharing an example; helped me to understand further  
4. contentUrl - I have explored this before, but will work on improving it using the suggestions you have provided.   
5. context manager (with open) 
6. temporary uploads - learned about it when reading the API docs., but seems it has many use cases.. reverse image search, large file uploads, etc.. are there any other uses that you use of? 

my selfhosted setup broke, so I just explored a few things before it died. Anyways, a lot of things learned in this conversation

thank you again both!! (@noirscape & @neobooru)
