### ISSUE TITLE
:d and :D

### ISSUE THREAD

**Issue by ewof** [rr-/szurubooru#585]
i have a :D tag for the facial expression i also want :d tag for the other facial expression but it says the tag already exists even tho one is uppercase and the other is lowercase

**Comment by neobooru** [comment]
As far as I can tell this is how most, if not all, other boorus work. Which means that I would be very hesitant to change this behavior. Additionally, all users so far have come to expect that tags are case insensitive.

This might not be the answer you were hoping for, but I currently don't know of a way to fix your issue in a non-breaking way.

**Comment by sgsunder** [comment]
By the way, you *can* use emojis as tag names. So for example you can have a tag named "😀" and have ":D" as an alias, and a tag named "😛" and maybe put something like ":d_" as an alias, so that when a user types either ":D" or ":d" they see both option suggested. Not a true solution but might be a good workaround for your use case.
