### ISSUE TITLE
error: what would cause this or has anyone encountered anything similar ?

### ISSUE THREAD

**Issue by closesttopurple** [rr-/szurubooru#691]
root@THEHUMANSERVER:~/szuru# docker compose up -d sql
WARN[0000] /root/szuru/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
[+] Running 0/1
 ⠼ Container szuru-sql-1  Starting                                         1.5s 
Error response from daemon: error while creating mount source path '/var/local/szurubooru/sql': mkdir /var/local: read-only file system

I have attempted to install this before a few times, but this is a new issue. I've tried to keep my settings close to what was default.

Let me know if I need to provide any other information.

**Comment by neobooru** [comment]
Well the error says that the container does not have permission to write to /var/local/szurubooru
Easy fix is probably the following
```sh
mkdir /var/local/szurubooru
chown -R 1000:1000 /var/local/szurubooru
```

Also see https://github.com/rr-/szurubooru/wiki/Common-errors and try searching in the [issues](https://github.com/rr-/szurubooru/issues) because someone else might've already had your issue in the past.
